const pickupLines = [
    "Are you a variable? Because you make my code look more beautiful.",
    "Are you a for loop? Because you repeat in my mind.",
    "Are you a function? Because you're the only one I want to call.",
    "Are you a bug in my code? Because you're driving me crazy.",
    "Are you a computer scientist? Because you always know how to turn me on.",
    "Are you a compiler? Because you make my code run smoothly.",
    "Are you a coding challenge? Because I want to spend hours with you.",
    "Are you a programmer? Because I'm getting lost in your code.",
    "Are you a null reference? Because you have no value to me.",
    "Are you a binary search tree? Because you're my only true love.",
    "Are you a variable? Because you're always on my mind.",
    "Is your name Google? Because you have everything I've been searching for.",
    "You must be a compiler, because you're turning my code into something beautiful.",
    "Are you a function? Because you add so much joy to my life.",
    "I must be a debugger, because I can't stop looking at your source code.",
    "Can I be the NULL in your life? Because without me, you'd be nothing.",
    "You must be a while loop, because I'm stuck in you forever.",
    "Are you a 2D array? Because I'm starting to get lost in your dimensions.",
    "Are you a stack? Because I'm trying to push my way into your life.",
    "You must be a linked list, because I'm always looking for the next node to connect with.",
    "Are you a lambda expression? Because you make my life more functional.",
    "I must be a garbage collector, because I can't stop thinking about you.",
    "Are you a design pattern? Because you're the solution to all my problems.",
    "You must be a version control system, because you're always on my mind.",
    "Are you a user story? Because you're exactly what I've been looking for.",
    "You must be a bug, because I can't stop thinking about you.",
    "You must be an API, because you always make me want to interface with you.",
    "Are you a Scrum Master? Because you're always helping me stay on track.",
    "Are you a code review? Because I want to see your best practices.",
    "You must be a continuous integration server, because you never let me down.",
    "Are you a unit test? Because you're always there to catch me when I'm failing.",
    "I must be a version number, because I'm always trying to increase my compatibility with you.",
    "You must be a software development methodology, because you're always guiding me in the right direction.",
    "Are you a user interface? Because you're always making me feel comfortable and welcomed.",
    "Are you a Python list? Because you're always expanding my horizons.",
    "You must be a Python dictionary, because you're always giving me keys to your heart.",
    "Are you a Python tuple? Because you're always there to support me.",
    "I must be a Python generator, because I can't stop producing thoughts about you.",
    "You must be a Python set, because you're always unique and distinct.",
    "Are you a Python object? Because you're always the center of my attention.",
    "Are you a Java class? Because you're always giving me a reason to instantiate you.",
    "You must be a Java exception, because you always catch my eye.",
    "Are you a Java thread? Because you always keep me on the edge of my seat.",
    "I must be a Java bytecode, because I can't stop being attracted to you.",
    "You must be a Java interface, because you're always providing me with a common set of methods.",
    "Are you a Java object? Because you're always the center of my attention.",
    "Are you a network cable? Because you're always connecting me to the right places.",
    "You must be a switch, because you always know how to turn me on.",
    "Are you a router? Because you're always routing me in the right direction.",
    "I must be a network interface, because I can't stop interfacing with you.",
    "You must be a network protocol, because you're always helping me communicate.",
    "Are you a network security system? Because you always keep me safe and protected.",
    "You have some features I’d like to collaborate on.",
    "Are you a list of sun emojis? Because I think you’re array of sunshine.",
    "I wanna checkout your backend.",
    "Honey, you are definitely full stack.",
    "You look like you have a full featured framework.",
    "I'd like to to inject a dependency in you.",
    "Can I get your SSL cert?",
    "Every time I see you my stack overflows.",
    "Are you a model? Because I’d like to train you.",
    "You turn my software into hardware.",
    "I'd love to look around your private repos.",
    "Are your eyes return statement? Cause i can’t get pass them",
    "My friend thinks you're a 10, but I told them you look more like a 1010.",
    "Hay, Wana go on an upDATE with me?",
    "Want to grab java some time?",
    "I don't want to objectify you, but I can't help noticing you have some wonderful attributes.",
    "Before we go any further, let's set up some parameters. I'm hoping to avoid having too many arguments.",
    "I'm hoping we could set up a one to one relationship.",
    "Are you an object oriented language? Cause you sure got class.",
    "Are you a ruby support library? Because you look like a gem.",
    "Are you a hashmap/dictionary? Because I think you have the key to my heart.",
    "I'd like to be in a linked list with you.",
    "Can you help me? Any time I try to reference you I come up with a no name error.",
    "Hay. Are you the one messing up my program... You must be! You are just too exceptional.",
    "Are you a subclass? Because if things go well I'm hoping you will introduce me to your parents.",
    "To make sure your not a bot, would you mind if I administers the turning test on you?",
    "Are you an os? Because you make my insides feel GUI.",
    "Do you use EDP? Because because meeting you is an event!",
    "You must be the internet, because I'm caught in your web.",
    "I think you should be saved as a constant. Because I wouldn't want to change a thing.",
    "Are you a branch? Cause I’d like to check you out",
    "Are you a master branch? Cause I will commit only to you with permission, and I’ll release on your command",
    "Are you an angel, because your texture mapping is divine!",
    "Roses are #FF0000, Violets are #0000FF, I use hex codes, But I’d use RGB for you!",
    "Git add your number to my phone, I want to commit",
    "Damn my data’s all out of sync because you increased the speed of my heartbeat",
    "You must be an IDE because you autocomplete me",
    "How'd you like to help me do some penetration testing?",
    "Baby you are the only person I wanna C#",
    "switch (goOutWithMe){case yes: console.log(„Hooray!“); case no: console.log(„Aww :(„); }",
    "Are you a data processor? Because I’d love for you to handle my dirty bits.",
    "You implement all the best traits",
    "How are you no-std but have --all-features?",
    "You derive me crazy",
    "Do you wanna be my mutable reference?",
    "Are you a SQL injection? Because seeing you makes me DROP JAW;",
    "Are you vim? Why can’t I quit you?"
]

export default pickupLines